en:
  languageCode: en-US
  languageName: "English"
  weight: 2

zh-cn:
  languageCode: zh-CN
  title: "888467 出海建站指南"
  languageName: "简体中文"
  params:
    description: "专注为出海独立开发者提供高效的技术解决方案。包含 Docker 运维、Linux 及开发工具教程。"
  weight: 1

# ja:
#   languageCode: ja-JP
#   languageName: "日本語"
#   weight: 3

# fr:
#   languageCode: fr-FR
#   languageName: "Français"
#   weight: 4

# de:
#   languageCode: de-DE
#   languageName: "Deutsch"
#   weight: 5

# es:
#   languageCode: es-ES
#   languageName: "Español"
#   weight: 6

# ru:
#   languageCode: ru-RU
#   languageName: "Русский"
#   weight: 7

